apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciohassen-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serviciohassen
  template:
    metadata:
      labels:
        app: serviciohassen
    spec:
      containers:
      - name: serviciohassen
        image: ghcr.io/hassen2208/serviciohassen:v1.0
        ports:
        - containerPort: 7005
      imagePullSecrets:
      - name: ghcr-secret



---

apiVersion: v1
kind: Service
metadata:
  name: serviciohassen-service
spec:
  selector:
    app: serviciohassen
  ports:
    - protocol: TCP
      port: 7005
      targetPort: 7005
  type: ClusterIP
