apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciomanuel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serviciomanuel
  template:
    metadata:
      labels:
        app: serviciomanuel
    spec:
      containers:
      - name: serviciomanuel
        image: ghcr.io/manuhcardoso1501/serviciomanuel:latest
        ports:
        - containerPort: 8069

---

apiVersion: v1
kind: Service
metadata:
  name: serviciomanuel
spec:
  selector:
    app: serviciomanuel
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
  type: ClusterIP