
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciojuanrodriguez
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serviciojuanrodriguez
  template:
    metadata:
      labels:
        app: serviciojuanrodriguez
    spec:
      containers:
      - name: serviciojuanrodriguez
        image: ghcr.io/silkenbread/service_juan_hotels:lastest
        ports:
        - containerPort: 8095

---

apiVersion: v1
kind: Service
metadata:
  name: serviciojuanrodriguez
spec:
  selector:
    app: serviciojuanrodriguez
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
  type: ClusterIP